### ISSUE TITLE
Question about training with multi-scale data augmentation

### ISSUE THREAD

**Issue by zhanggang001** [wxzs5/direct-pretraining#4]
Hi, Yang Li, I wonder that if you have tried direct-pretraining and fine-tuning with multi-scale data augmentation (like that in detectron2). I observe that under the current training strategy, models will be overfitted if being fine-tuned with a schedule longer than 1x. On the other hand, the way proposed by **Rethinking ImageNet Pre-training** (i.e. training detectors from scratch with GN and longer schedule) can benefit more from multi-scale data augmentation during training. Thank you in advance.

**Comment by wxzs5** [comment]
We have discussed fine-tuning with multi-scale augmentation in Sec 4.5 for comparsion to ImageNet. As for scratch training(GN) with multi-scale strategy, e.g., in detectron2 it utilizes  `Large-Scale Jitter`  strategy can get better performance. But in our recent experiments shows that if our pre-trained model fine-tuning with similar  `Large-Scale Jitter`  or other proper multi-scale strategy, our models will still be slightly better and not overfitted.

**Comment by zhanggang001** [comment]
> We have discussed fine-tuning with multi-scale augmentation in Sec 4.5 for comparsion to ImageNet. As for scratch training(GN) with multi-scale strategy, e.g., in detectron2 it utilizes `Large-Scale Jitter` strategy can get better performance. But in our recent experiments shows that if our pre-trained model fine-tuning with similar `Large-Scale Jitter` or other proper multi-scale strategy, our models will still be slightly better and not overfitted.

`fine-tuning with similar Large-Scale Jitter or other proper multi-scale strategy` also uses the same fine-tuning schedule as in your paper? only change the data augmentation strategy?

**Comment by wxzs5** [comment]
Yes, with that scale strategy, we observe that fine-tuning w/ 1x, 2x, 3x schedules still not be overfitted.

**Comment by zhanggang001** [comment]
Thank you！
